function csv2html(csvFile, title, htmlFile)
% CSV to HTML
%   This function converts CSV files generated by chatstats to HTML files
%   specifically for use with the chatstats-capproject website. This
%   function takes three strings as input. csvFile is the name of the file
%   to convert, title is the desired title for the data table, and htmlFile
%   is the name of the file to be created.

csv = fopen(['raw/' csvFile]);
data = [];
fprintf('Converting %s to HTML...\n', csvFile);
while feof(csv) == 0
    line = strsplit(fgetl(csv),',');
    data = [data; line];
end
fclose(csv);
html = fopen(['stats/' htmlFile], 'w');
fprintf(html, ['<!DOCTYPE html><html lang="us"><head><meta charset=''UT'...
    'F''-8''><title>chatstats</title><link type="text/css" rel="stylesh'...
    'eet" href="https://sparktrain.github.io/chatstats-capproject/style'...
    '.css"></head><body><h1>chatstats</h1><h2><a href="http://play.poke'...
    'monshowdown.com/capproject">PS! CAP Project Room</a></h2><table><c'...
    'aption><h3>' title '</h3></caption><thead><tr>']);
j = 1;
while j <= size(data, 2)
    x = data(1,j);
    fprintf(html, ['<th>' x{1} '</th>']);
    j = j + 1;
end
fprintf(html, '</tr></thead><tbody>');
i = 2;
while i <= size(data, 1)
    fprintf(html, '<tr>');
    j = 1;
    while j <= size(data, 2)
        x = data(i,j);
        fprintf(html, ['<td>' x{1} '</td>']);
        j = j + 1;
    end
    fprintf(html, '</tr>');
    i = i + 1;
end
fprintf(html, '</tbody></table></body></html>');
fprintf('%s has been successfully generated and saved at %s\n', title, ...
    ['stats/' htmlFile]);
fclose(html);

end